import Head from "@/components/Portfolio/Head/Head";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Portfolio/Header/header";
import Footer from "@/components/Portfolio/Footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
